apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-service
  namespace: pianops
  labels:
    app: exercises-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises-service
  template:
    metadata:
      labels:
        app: exercises-service
    spec:
      containers:
        - name: exercises-service
          image: acrpianops.azurecr.io/exercises-service:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: exercises-service
  namespace: pianops
spec:
  selector:
    app: exercises-service
  ports:
    - port: 8000
      targetPort: 8000
